# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Functional test suite

on:
  pull_request_review:
    types: [ submitted ]

jobs:
  build-snap:
    name: Build snap
    runs-on: ubuntu-latest
    if: >-
      github.event.review.state == 'approved'
      || github.event.review.body == 'recheck-snap'
      || github.event.review.body == 'recheck-full'
    outputs:
      code-changed: ${{ steps.code-changed.outputs.changed }}
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: snapcraft
    - name: Install snap
      run: sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
    - name: Track changed files in the PR
      id: code-changed
      run: |
        git remote add upstream https://github.com/canonical/juju-verify
        git fetch upstream master
        failed=0
        git diff --name-only upstream/master | grep -qE '^(juju_verify|tests)' || failed=1
        echo "::set-output name=changed::$failed"

  func-tests:
    name: Integration tests
    runs-on: self-hosted
    needs: build-snap
    if: >-
      (
        github.event.review.state == 'approved'
        && needs.build-snap.outputs.code-changed == 0
      )
      || github.event.review.body == 'recheck-full'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Run func tests
        run: |
          source ~/novarc
          tox -e func

