# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test suite

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review, edited ]
    branches: [ master ]

  pull_request_review:
    types: [ submitted ]

jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - name: print
        env:
          COMMENT: ${{ toJSON(github.event.comment) }}
          PR: ${{ toJSON(github.event.pull_request) }}
          PR_COMMENTS: ${{ toJSON(github.event.pull_request.comments) }}
          PR_STATUSES: ${{ toJSON(github.event.pull_request.statuses) }}
        run: |
          echo "comment=$COMMENT"
          echo "=========================================================="
          echo "PR=$PR"
          echo "=========================================================="
          echo "comments=$PR_COMMENTS"
          echo "=========================================================="
          echo "statuses=$PR_STATUSES"

  lint-unittests-docs-build:
    name: Lint, Unit tests, Docs and Build
    runs-on: ubuntu-latest
    if: >-
      github.event.pull_request
      || (
        github.event.comment.body == 'recheck-snap'
        || github.event.comment.body == 'recheck-full'
      )
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Run lint checkers
      run: tox -e lint
    - name: Run unit tests
      run: tox -e unit
    - name: Build docs
      run: tox -e docs
    - name: Build package
      run: tox -e build
    - name: Verify package
      run: tox -e build-verify

  build-snap:
    name: Build snap
    runs-on: ubuntu-latest
    needs: lint-unittests-docs-build
    if: >-
      github.event.review.state == 'approved'
      || (
        github.event.comment.body == 'recheck-snap'
        || github.event.comment.body == 'recheck-full'
      )
    outputs:
      code-changed: ${{ steps.code-changed.outputs.changed }}
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: snapcraft
    - name: Install snap
      run: sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
    - name: Track changed files in the PR
      id: code-changed
      run: |
        git remote add upstream https://github.com/canonical/juju-verify
        git fetch upstream master
        failed=0
        git diff --name-only upstream/master | grep -qE '^(juju_verify|tests)' || failed=1
        echo "::set-output name=changed::$failed"

  func-tests:
    name: Integration tests
    runs-on: self-hosted
    needs: build-snap
    if: >-
      (
        github.event.review.state == 'approved'
        && needs.build-snap.outputs.code-changed == 0
      )
      || github.event.comment.body == 'recheck-full'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Run func tests
        run: |
          source ~/novarc
          tox -e func

